# Generated by Django 2.0.4 on 2023-03-28 20:00

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='InsuranceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_detail_title', models.CharField(max_length=30, verbose_name='Insurance Detail')),
            ],
            options={
                'verbose_name': 'Insurance Detail',
                'verbose_name_plural': 'Insurance Details',
            },
        ),
        migrations.CreateModel(
            name='InsuredPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('surname', models.CharField(max_length=180, verbose_name='Surname')),
                ('age', models.CharField(default='', max_length=180, verbose_name='Age')),
                ('address', models.CharField(default='', max_length=180, verbose_name='Address')),
                ('insurance_detail', models.ManyToManyField(to='insurance_database.InsuranceDetail')),
            ],
            options={
                'verbose_name': 'Insured Person',
                'verbose_name_plural': 'Insured Persons',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=80, verbose_name='Insurance')),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurances',
            },
        ),
        migrations.AddField(
            model_name='insuredperson',
            name='insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance_database.Insurance', verbose_name='Type of Insurance'),
        ),
    ]

